Load balancer client with register
NodeFactoryIo/vedran-daemon pull request #11
Opened 2020-09-15 09:01 UTC by mpetrun5

Closes: #5

2020-09-15 09:55 UTC, MakMuftic approved these changes

2020-09-16 08:43 UTC, mpetrunic requested changes

2020-09-16 08:43 UTC, mpetrunic commented on internal/lb/client.go
> +	req, _ := c.NewRequest(http.MethodPost, registerEndpoint, body)
you could have malformed url error here

2020-09-16 08:43 UTC, mpetrunic commented on internal/lb/client.go
> +func (c *Client) NewRequest(method string, urlStr string, body interface{}) (*http.Request, error) {
Don't export NewRequest and Do method

2020-09-16 10:43 UTC, MakMuftic approved these changes

2020-09-16 11:17 UTC, mpetrun5 commented on internal/lb/client.go
> +	BaseURL *url.URL
url.Parse doesn't return error for invalid url
Will need to check that differently

2020-09-16 11:25 UTC, mpetrun5 commented on internal/lb/client.go
> +	BaseURL *url.URL
Checked and should be fine
NewRequest still returns req and do fails as it should

2020-09-16 12:59 UTC, mpetrunic approved these changes

2020-09-16 12:59 UTC, merged