Repo cleanup
NodeFactoryIo/vedran-daemon pull request #12
Opened 2020-09-15 10:29 UTC by mpetrun5

- update codeowners
 - remove config files 
 - update README
 - update Dockerfile 
 - add actions dependency caching

2020-09-15 15:47 UTC, MakMuftic requested changes

2020-09-15 15:47 UTC, MakMuftic commented on Dockerfile
> +RUN cp /build .
I think this will make the same problem, so I think that the best solution is
`RUN cp /build/vedran-daemon .`

2020-09-16 08:10 UTC, mpetrunic commented on .github/workflows/test.yml
> +            ${{ runner.os }}-go-
this need to go after "Checkout code" step

2020-09-16 08:10 UTC, mpetrunic commented on Dockerfile
> +FROM scratch
can we use pure alpine, so we can add native dependencies and sh into container if needed

2020-09-16 08:18 UTC, mpetrunic approved these changes

2020-09-16 10:45 UTC, MakMuftic approved these changes

2020-09-16 10:46 UTC, merged