Config hash logic
NodeFactoryIo/vedran-daemon pull request #19
Opened 2020-09-18 13:38 UTC by mpetrun5

Closes: #4

2020-09-19 10:49 UTC, mpetrunic requested changes

2020-09-19 10:49 UTC, mpetrunic commented on internal/node/client.go
> +func (client *client) sendRPCRequest(method string, params []string, v interface{}) (*http.Response, error) {
considering our use case, it would probably be better to use batch json rpc requests. Pls open issue for that but we would deal with that later

2020-09-19 10:49 UTC, mpetrunic commented on internal/node/hash.go
> +	JSONRPC string `json:"jsonrpc"`
you might wanna add common properties to some generic type JsonRpcResponse, and reference it in every method response type

2020-09-19 10:49 UTC, mpetrunic commented on internal/node/hash.go
> +	_, _ = hash.Write([]byte(string(properties.TokenSymbol)))
sort config properties alphabetically. Examle chain should be before methods etc

2020-09-21 08:40 UTC, MakMuftic approved these changes

2020-09-21 13:32 UTC, MakMuftic approved these changes

2020-09-21 13:49 UTC, MakMuftic approved these changes

2020-09-21 13:50 UTC, mpetrunic approved these changes

2020-09-21 13:50 UTC, merged